### ISSUE TITLE
Renderでバックエンドのルートディレクトリをbackendディレクトリに指定する

### ISSUE THREAD

**Issue by wassupdee** [wassupdee/pomodoro_timer_app_new#52]
### 概要
Renderでバックエンドのルートディレクトリをbackendディレクトリに指定する

---
### 背景・目的
`backend`ディレクトリ内にある`Gemfile`が見つからないというエラーが、デプロイ時発生したため

---
### タスク
- [x] `render.yaml`で、バックエンドのルートディレクトリを`backend`ディレクトリに指定する
- [x] buildCommandのパスから、`backend`ディレクトリを削除する
```
services:
...
    rootDir: backend 
    buildCommand: "./bin/render-build.sh"
```
